spring.application.name=courses
spring.datasource.url=jdbc:postgresql://localhost:5432/cources
spring.datasource.username=kben-tou
spring.datasource.password=""
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=postgresql
